### ISSUE TITLE
Does Not Work with new Gemini 1.5 Models

### ISSUE THREAD

**Issue by bruglet** [greycodee/gemini-terminal#4]
Using the app with any of the Gemini 1.5 models (`gemini-1.5-pro-latest` and `gemini-1.5-flash-latest`) does not work and only responds with a 404 error from googleapi.

Upon sending any message, no response is generated, and this message appears in the chat box.
![image](https://github.com/greycodee/gemini-terminal/assets/56103194/a08d7c98-2665-4df1-9718-8a0b2dca159a)

Switching to `gemini-1.0-pro` works for the meantime, however, this should be fixed since 1.5-flash is an improvement in every way over 1.0-pro.

I tried fixing it myself but I have very minimal Go knowledge so I didn't get far...

**Comment by greycodee** [comment]
Now that it's working, you can pull the latest code from the main branch and rebuild it to use it.

**Comment by bruglet** [comment]
Can confirm it's fixed now, thanks for the help and hard work 👍
